### ISSUE TITLE
【紧急！！】 由于此项目中newSHARE文件夹里是公司内部代码，烦请删除此仓库！！！

### ISSUE THREAD

**Issue by KingAmo** [Cliqin/SHARE#1]
此 `项目` 中 `newSHARE` 文件夹里是公司内部代码，烦请删除此仓库，谢谢！

**Comment by KingAmo** [comment]
@xiaomihu69 @1077602679 @guangg1g   烦请删除此仓库

**Comment by Cliqin** [comment]
ok

**Comment by 1077602679** [comment]
哈，什么东西

**Comment by KingAmo** [comment]
不仅是readme哦，整个文件夹麻烦删除一下哈，代码中有接口路径等相关信息哦，谢谢~
